### ISSUE TITLE
Build not working "from box"

### ISSUE THREAD

**Issue by Indomian** [christophehurpeau/html-document#13]
Build not working after cloning project. Seems there should be some step creating links to required modules to **node_modules** from **springbokjs-library**. 
For now to make project working i should install locally all these libraries, that are purged after **make install** or **make update**:
```bash
npm install babel-eslint babelify babel-plugin-add-jsdoc-properties jscs gulp babel jaguarjs-jsdoc
```

**Comment by christophehurpeau** [comment]
make install doesn't work after cloning project. You have to use `npm install`
I don't have any problem. Can you paste the error ? the version of node and npm you use ?
