### ISSUE TITLE
Add building information

### ISSUE THREAD

**Issue by Indomian** [christophehurpeau/html-document#5]
Please provide information about configuration of developing enviroment.
Now it's not clear which packages are required, and which commands for make and gulp can be used.

**Comment by christophehurpeau** [comment]
Does that help ? https://github.com/christophehurpeau/html-document/blob/master/CONTRIBUTING.md

**Comment by Indomian** [comment]
Yep! Thats cool. Btw on last update 

    npm install

seems to be broken (it starts make install somehow).
